version: '3.3'

services:
  db:
    image: postgres:13.4
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5450:5432"
    environment:
      POSTGRES_USER: fastapi_db
      POSTGRES_PASSWORD: fastapi_db
      POSTGRES_DB: fastapi_db
      TZ: GMT+3
    healthcheck:
      test: pg_isready -U fastapi_db -d fastapi_db
      interval: 30s
      timeout: 3s
      retries: 3

volumes:
  postgres_data: