"""sessiontoken

Revision ID: 9c6c92e3bbc0
Revises: e0325effd6ee
Create Date: 2022-07-06 13:27:40.508282

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9c6c92e3bbc0"
down_revision = "e0325effd6ee"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tokens_id", table_name="tokens")
    op.create_index(op.f("ix_tokens_id"), "tokens", ["id"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tokens_id"), table_name="tokens")
    op.create_index("ix_tokens_id", "tokens", ["id"], unique=False)
    # ### end Alembic commands ###
